name = "GXBeamCS"
uuid = "ecf8e379-0620-438b-a5cb-8c0af8704d10"
authors = ["Andrew Ning <aning@byu.edu>", "Adam Cardoza"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
